### ISSUE TITLE
KyberKeyAgreement.java

### ISSUE THREAD

**Issue by husheng1997** [fisherstevenk/kyberJCE#14]
There are bugs in the decryption functions。
for example, in decrypt768:
for (int i = 0; i < KyberParams.paramsSymBytes; i++) {
            int length = KyberParams.Kyber768SKBytes - KyberParams.paramsSymBytes + i;
            byte[] skx = new byte[length];
            System.arraycopy(privateKey, 0, skx, 0, length);
            kr[i] = (byte) ((int) (kr[i] & 0xFF) ^ ((int) (fail & 0xFF) & ((int) (kr[i] & 0xFF) ^ (int) (skx[i] & 0xFF))));
        }
This code copies the first length bytes of privateKey to skx， which is part of IND-CPA-Private.
However, what actually needs to be copied is the randomBytes('z' in 《Endemic Oblivious Transfer》)
（2 * KyberParams.Kyber768SKBytes + 2 * KyberParams.paramsSymBytes, KyberParams.Kyber1024SKBytes）

**Comment by fisherstevenk** [comment]
Thank you.  I'll take a look into this at some point today.

**Comment by fisherstevenk** [comment]
Original C method:
https://github.com/pq-crystals/kyber/blob/master/avx2/kem.c

Equivalent Java code:
https://github.com/fisherstevenk/kyberJCE/blob/main/src/main/java/com/swiftcryptollc/crypto/provider/KyberKeyAgreement.java

RE: kem.c:94 ->  int crypto_kem_dec
     KyberKeyAgreement:374 ->  decrypt768(...)  (but also applies to decrypt512(..) and decrypt1024(..))

Variable equivalents:
kem.c: 96 ->  sk = pointer to input private key
KyberKeyAgreement: 376 -> privateKey (and “this.x”)
 
kem.c Line 121/122: cmov(kr, sk+KYBER_SECRETKEYBYTES-KYBER_SYMBYTES, KYBER_SYMBYTES, fail);

cmov defined in https://github.com/pq-crystals/kyber/blob/master/avx2/verify.c

Variable equivalents:
kem.c:102 -> kr = array of 64 bytes
Kem.c: 176 -> hc gets copied to the last 32 bytes of kr 
KyberKeyAgreement.java:390 -> kr (array of the first 32 bytes) + KyberKeyAgreement.java:398 -> krh (array of the last 32 bytes = ‘hc’ in kem.c)
KyberKeyAgreement.java:405 -> tempBuf = krh appended to kr

If fail == 1, cmov will copy -> sk+KYBER_SECRETKEYBYTES-KYBER_SYMBYTES to kr

Where:
sk+KYBER_SECRETKEYBYTES-KYBER_SYMBYTES points to the start of the last 32 bytes of sk (or the last 32 bytes of privateKey for Java)
kr points to the beginning of the kr array, or effectively kr[0] in Java reference.
KYBER_SYMBYTES = 32 bytes

Break down cmov:

r = rvec = kr (64 bytes)
x = xvec = sk+KYBER_SECRETKEYBYTES-KYBER_SYMBYTES (pointer to sk[length - 32] -> sk[2400-32] -> sk[2368])
KYBER_SECRETKEYBYTES = (KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + 2*KYBER_SYMBYTES)
KYBER_INDCPA_SECRETKEYBYTES = (KYBER_POLYVECBYTES)
KYBER_POLYVECBYTES = (KYBER_K * KYBER_POLYBYTES)
KYBER_K = 3 (for 768) * KYBER_POLYBYTES = 384
+= 1152
+ KYBER_INDCPA_PUBLICKEYBYTES = (KYBER_POLYVECBYTES + KYBER_SYMBYTES)
KYBER_POLYVECBYTES = (KYBER_K * KYBER_POLYBYTES)
KYBER_K = 3 (for 768) * KYBER_POLYBYTES = 384
+= 1152
KYBER_SYMBYTES
+= 32
+ 2 * KYBER_SYMBYTES (32)
+= 64
= 2400 (1152 + 1152 + 32 + 64)
-= 32
= 2368

len = KYBER_SYMBYTES (32)
b = 0 || 1 (1 == fail)

void cmov(uint8_t * restrict r, const uint8_t *x, size_t len, uint8_t b)
{
  size_t i;
// 256 bit integer vectors (32 bytes)
  __m256i xvec, rvec, bvec;

  // Create a vector with all elements set to the specified scalar integer value.
  bvec = _mm256_set1_epi64x(-(uint64_t)b);

// len/32 = 32/32 = 1; loop only goes through once
  for(i=0;i<len/32;i++) {

// _mm256_loadu_si256 Loads integer values from the 256-bit (32 bytes) unaligned 
// memory location pointed to by *a, into a destination integer vector, 
// which is returned by the intrinsic.
    rvec = _mm256_loadu_si256((__m256i *)&r[32*i]);
    xvec = _mm256_loadu_si256((__m256i *)&x[32*i]);
// _mm256_blendv_epi8 Each byte element of the destination vector is copied from the 
// corresponding byte element in s2 if a mask bit is 1, or the corresponding byte 
// element in s1 if a mask bit is 0.

// if b = 0, rvec = rvec -> unmodified
// if b = 1, rvec = xvec -> copy bytes from sk starting at index = sk.length - 32 + i (0)
    rvec = _mm256_blendv_epi8(rvec,xvec,bvec);
// _mm256_storeu_si256 Performs a store operation by moving integer values from
// a 256-bit integer vector, b, to a 256-bit unaligned memory location, 
// pointed to by a.

// i = 0, so simply move rvec (32 bytes) back to r (overwriting the first 32 bytes of kr with rvec))
    _mm256_storeu_si256((__m256i *)&r[32*i],rvec);
  }

// i = 1
// r will now point to index 32 (kr[32] or krh for Java code)
  r += 32*i;
// x will now point to the END of sk
  x += 32*i;
// 32 * i = 32, len = 32.. 32 - 32 = 0
  len -= 32*i;
// for i = 0, i < 0… won’t execute
  for(i=0;i<len;i++)
    r[i] ^= -b & (x[i] ^ r[i]);
}


Summary of cmov

If fail = 0 (meaning success)
Copy the first 32 bytes of kr to the first 32 bytes of kr

If fail == 1 (actual failure)
Copy the last 32 bytes of the private key to the first 32 bytes of kr



Breakdown of the equivalent code within decrypt768(..) (KyberKeyAgreement: 374)

// Loop from 0 to 32
  for (int i = 0; i < KyberParams.paramsSymBytes; i++) {
	// length = 2400 - 32 + i
            int length = KyberParams.Kyber768SKBytes - KyberParams.paramsSymBytes + i;
	// create new array skx of calculated length
            byte[] skx = new byte[length];
	// Copy the privateKey (sk) to skx
            System.arraycopy(privateKey, 0, skx, 0, length);
	// skx[i]; i = 0 to 32;  skx will pull from privateKey[0-31]/sk[0-31]
// instead of sk[length-32 to length-1]
            kr[i] = (byte) ((int) (kr[i] & 0xFF) ^ ((int) (fail & 0xFF) & ((int) (kr[i] & 0xFF) ^ (int) (skx[i] & 0xFF))));
        }

Code changed to:

        // index will point to the beginning of the last 32 bytes of privateKey
        int index = KyberParams.Kyber768SKBytes - KyberParams.paramsSymBytes;
       // i = 0 to 31
        for (int i = 0; i < KyberParams.paramsSymBytes; i++) {
	// if (fail == 0) -> kr[i] = kr[i]
	// if (fail == 1) -> kr[i] = kr[i] ^ (kr[i] ^ privateKey[index]) = privateKey[index]
            kr[i] = (byte) ((int) (kr[i] & 0xFF) ^ ((int) (fail & 0xFF) & ((int) (kr[i] & 0xFF) ^ (int) (privateKey[index] & 0xFF))));
            index += 1;
        }

Fixed in Pull Request #15 and updated the pom version in #16
